### ISSUE TITLE
[BUG] The search does not work in Russian.

### ISSUE THREAD

**Issue by Fertion** [scambier/obsidian-text-extractor#1]
**Problem description:**

The search does not work in russian. In the settings "rus" is added. At the same time, when I do a search in english and see the text in russian in the search results, I see that it is displayed in Latin characters, and not in Cyrillic characters, as it should be.

For example, instead of the russian word "Депозитарий" the text is recognized as "Jenosutapuu", i.e. the words are clearly not recognized in the correct language.
![image](https://user-images.githubusercontent.com/102726751/212493921-214ef47d-be53-4ae0-b6f4-f555a90b6107.png)
![image](https://user-images.githubusercontent.com/102726751/212493970-aeb8c921-81b3-41a9-a346-21a1e90089b0.png)

**Your environment:**

- Plugin version: 0.2.0
- Obsidian version: 1.1.9
- Operating system: Windows 10
- Number of images/PDFs in your vault (approx.): ~130
- Other plugins that may be related to the issue: Omnisearch 1.10.0

**Comment by scambier** [comment]
This should be fixed with the latest release, you may have to clear the cache.

**Comment by Fertion** [comment]
Installed 0.4.0, but it still does not work.
Removed the cache data, also completely uninstalled the plugin, and then installed anew, but it did not help.

Also does not work with all languages using the characters in Cyrillic: Urkaine, Belorussian and others.

Here's another example of using the function "Extract Text into a new note".

![image](https://user-images.githubusercontent.com/102726751/213927713-9d7ca130-4cef-4925-9c46-d33f6b137495.png)

**Comment by Fertion** [comment]
I found that the characters in Cyrillic are correctly recognized if you select only one language "rus", but if you add a 2nd language "eng" the problem returns.

**Comment by scambier** [comment]
The problem is (IMO) Tesseract that sees your screenshot and wrongly assumes that it's English, even though Russian is also in the list. I'll add a contextual action to force a specific language when extracting

**Comment by Onkitova** [comment]
I think I found a root of the problem and a fix for this and similar issue https://github.com/scambier/obsidian-text-extractor/issues/30 with Chinese.

After reading [tesseract.js README](https://github.com/naptha/tesseract.js#tesseractjs) and this syntax specifically:

![image](https://github.com/scambier/obsidian-text-extractor/assets/119720012/0c35ea2a-7a5f-4a7c-bed4-b84907aee099)
I tried to manipulate data.json settings file in Text Extractor plugins main folder in such manner:

![image](https://github.com/scambier/obsidian-text-extractor/assets/119720012/bb56c522-1c7c-4b5d-976b-dec1d172c655)
and it actually fixed the problem -- now OCR **works** for two languages at the same time:

![sample image _english-russian_](https://github.com/scambier/obsidian-text-extractor/assets/119720012/5daf67b6-dcca-451c-a041-5222255383ea)

I'm not fluent enough in JS, but my guess is that when plugin passing the argument responsible for the language ("ocrLanguages") to the tesseract.js function, there is an error, and instead of passing "eng+rus" or "eng+chi_tra" it throws an error and then uses "eng" **as a fallback argument**. I think so, because if we manually set two non-latin languages like this:

![image](https://github.com/scambier/obsidian-text-extractor/assets/119720012/4ad2af4e-f6c4-4bc4-9e38-0d8f9e88cc6c)

OCR still manages to read latin English from my sample image above (while corrupting Russian symbols):

![image](https://github.com/scambier/obsidian-text-extractor/assets/119720012/8971ea9f-94ed-4f16-8719-5bc1b62f8217)

Please check this out.

**Comment by scambier** [comment]
Good find.

So what's happening is that when you configure multiple languages like `["eng", "rus"]`, they are concatenated to `"eng+rus"` before being passed to Tesseract. But there's a bug, right here:

https://github.com/scambier/obsidian-text-extractor/blob/65d3a5ec5ef48cd083db5ba631ddb374cec153be/lib/src/ocr/ocr-manager.ts#L58-L59

The first line loads the languages `"eng+rus"` (the concatenated string), but the second line only initializes the first language from the array `["eng", "rus"]`. Editing data.json with `["eng+rus"]` instead of `["eng", "rus"]` effectively bypasses this bug.

**Comment by scambier** [comment]
@Onkitova @Fertion I've published a new version that should fix this. Can you confirm it's ok for you?

**Comment by Fertion** [comment]
Yes, the recognition now works in several languages simultaneously. Thank you.

**Comment by Onkitova** [comment]
> @Onkitova @Fertion I've published a new version that should fix this. Can you confirm it's ok for you?

Yes. Thanks!
